### ISSUE TITLE
service:// surfaces do not resolve target service claw.skill.emit skills

### ISSUE THREAD

**Issue by mostlydev** [mostlydev/clawdapus#54]
## Summary

`service://...` surfaces currently do not resolve the target service's `claw.skill.emit` metadata when wiring skills into the consuming agent.

As a result, agents that declare a surface like `service://trading-api` only receive the generic fallback `surface-trading-api.md` connection stub, not the authoritative skill file emitted by the `trading-api` image.

This is a direct mismatch with both the design intent and the comments/docs in the example.

## Why this matters

The point of `claw.skill.emit` is that a service can ship its own usage manual and Clawdapus will surface that manual to agents that are allowed to talk to it.

That matters most for API-style services where the difference between a generic connection stub and the real workflow is large:

- endpoint inventory
- request/response shape
- approval flow / state machine
- ordering of operations
- safety constraints
- examples

Without the emitted skill, agents only know that the service exists on the network. They do not get the service-authored operational manual that the feature is supposed to deliver.

## Concrete example in this repo

`examples/trading-desk/Dockerfile.trading-api` says:

- `LABEL claw.skill.emit=/app/skills/trade.md`

The file comment says this should cause Clawdapus to extract `trade.md` from the service image and mount it into every claw that declares `surface: service://trading-api`.

That is not what the current compose path does.

### What happens today

During `claw up`, for each Claw-managed service, `cmd/claw/compose_up.go` does the following:

1. inspects the Claw service image itself
2. resolves image-level skills for that Claw service
3. optionally extracts `info.SkillEmit` for that Claw service image
4. generates fallback service-surface skills for declared `service://...` surfaces

This means `info.SkillEmit` is only applied to the current agent's own image, not to the target service image referenced by the surface.

### The relevant gap

In `cmd/claw/compose_up.go`:

- the `info.SkillEmit` block only considers the current service image
- `resolveServiceGeneratedSkills()` later creates fallback `surface-<target>.md` files for service surfaces
- there is no step that inspects `p.Services[surface.Target]` and resolves/extracts its `claw.skill.emit`

So for a surface like `service://trading-api`, the agent gets the fallback stub, not `trade.md` from the `trading-api` image.

## Observed impact

In the trading-desk example, the agent presents as a generic momentum trader but does not appear to have the actual trading workflow/API manual in context.

That makes the example look like a prompt failure when the real bug is that the surface skill plumbing is incomplete.

Specifically:

- `examples/trading-desk/agents/WESTIN.md` tells the agent that the trading-api surface skill describes endpoints and workflow
- the `trading-api` image advertises an emitted skill file
- but the consuming agent only gets the fallback `surface-trading-api.md` connection note

## Reproduction

1. Build the trading-desk example and the `trading-api` image.
2. Run `claw up -d -f examples/trading-desk/claw-pod.yml`.
3. Inspect the mounted skills for an agent with `service://trading-api`.
4. Compare the mounted files to the service-emitted file promised by the image label.

Expected:

- the consuming agent receives the service-authored trading skill from the `trading-api` image

Actual:

- the consuming agent gets the generic generated fallback for `surface-trading-api.md`
- the service-emitted `trade.md` is not resolved through the surface relationship

## Expected behavior

When a Claw-managed service declares `service://<target>`, Clawdapus should inspect the target service definition and prefer the target service's emitted skill if one exists.

A reasonable precedence model would be:

1. target service `claw.skill.emit`
2. operator override skill for that surface, if any
3. generated fallback `surface-<target>.md`

## Naming/UX detail that also needs a decision

There is a secondary design question here:

- current surface docs/indexing assume service skills are named `surface-<target>.md`
- emitted service skills preserve the basename from the service image (for example `trade.md`)

That means the fix should choose one consistent behavior:

- either mount emitted skills under the surface slot name (`surface-trading-api.md`)
- or preserve `trade.md` and update `CLAWDAPUS.md` / skill indexing so the agent is pointed at the right file

Right now the codebase implies both patterns in different places.

## Acceptance criteria

- `service://...` resolution inspects the target service image for `claw.skill.emit`.
- If present, the emitted skill is extracted and mounted into the consuming agent.
- Fallback surface skill generation only happens when the target service does not emit a skill or extraction fails.
- The skill name shown in `CLAWDAPUS.md` matches the actual mounted file path.
- A regression test covers the `examples/trading-desk` shape or an equivalent fixture.
- README/example comments no longer over-promise behavior that the compose path does not implement.

## Related files

- `cmd/claw/compose_up.go`
- `internal/runtime/service_skill.go`
- `internal/driver/shared/clawdapus_md.go`
- `examples/trading-desk/Dockerfile.trading-api`
- `examples/trading-desk/agents/WESTIN.md`
- `README.md`

## Notes

This issue is not about whether skill extraction works in isolation. The extraction helper exists. The bug is that surface wiring never consults the target service's emitted skill when building the consuming agent's skill set.
